# Generate SSD1306-style framebuffer blobs for oled.c (128-wide pages, MSB top pixel in byte)
import os

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    raise SystemExit("pip install pillow")

PHRASES = [
    "丢线",
    "往左修正",
    "往右修正",
    "巡线中",
    "雷达判定中",
]

# Small HUD line (oled.c top-left row 2): Chinese label before path distance (m) digits
SMALL_LABELS = [
    ("行驶距离=", "dist_lbl", 14, 16),
]

# Top-right HUD: map detect (|px| vs 0.5 m) -> mirror locked; path distance shown in m
TRACK_HUD = [
    ("左赛道", "trk_l", 14, 16),
    ("右赛道", "trk_r", 14, 16),
    ("未选择", "trk_u", 14, 16),
]

# 雷达 USART 选支路完成后 OLED 显示约 2s（与 LineTracking 中宏一致）
RADAR_PICK = [
    ("雷达选择左边", "radar_pick_l"),
    ("雷达选择右边", "radar_pick_r"),
]

FONT_CANDIDATES = [
    r"C:\Windows\Fonts\simhei.ttf",
    r"C:\Windows\Fonts\msyh.ttc",
    r"C:\Windows\Fonts\simsun.ttc",
]


def find_font(size):
    for p in FONT_CANDIDATES:
        if os.path.isfile(p):
            return ImageFont.truetype(p, size)
    return ImageFont.load_default()


def to_pages(img_mono):
    """img: L mode, 0=black bg, 255=lit pixel. Return bytes column-major within each 8-row page (SSD1306 horiz mem)."""
    w, h = img_mono.size
    assert h % 8 == 0
    pages = h // 8
    out = bytearray()
    for p in range(pages):
        y0 = p * 8
        for x in range(w):
            val = 0
            for bit in range(8):
                y = y0 + bit
                if x < w and y < h:
                    if img_mono.getpixel((x, y)) > 128:
                        val |= 1 << bit
            out.append(val)
    return bytes(out)


def render_phrase(text, font_size=18, pad=4, target_h=32):
    font = find_font(font_size)
    tmp = Image.new("L", (256, 64), 0)
    dr = ImageDraw.Draw(tmp)
    bbox = dr.textbbox((0, 0), text, font=font)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    w = tw + pad * 2
    h = target_h
    # pad to multiple of 8 vertically
    if h % 8:
        h = (h + 7) // 8 * 8
    im = Image.new("L", (w, h), 0)
    dr = ImageDraw.Draw(im)
    ox = pad - bbox[0]
    oy = (h - th) // 2 - bbox[1]
    dr.text((ox, oy), text, font=font, fill=255)
    return im


def emit_bmp(out_lines, name, im):
    w, h = im.size
    blob = to_pages(im)
    out_lines.append(f"\nconst uint8_t oled_bmp_{name}[] = {{")
    for j in range(0, len(blob), 16):
        chunk = blob[j : j + 16]
        hx = ", ".join(f"0x{b:02X}u" for b in chunk)
        out_lines.append("  " + hx + ",")
    out_lines.append("};")
    out_lines.append(f"const uint16_t oled_bmp_{name}_w = {w}u;")
    out_lines.append(f"const uint8_t oled_bmp_{name}_h = {h}u;")


def main():
    out_lines = []
    out_lines.append("/* Auto-generated by tools/gen_oled_cn_bmps.py — 16-gray to 1bpp */")
    out_lines.append("#include <stdint.h>")
    # Center status: larger font for 1.3 inch panel (clearer strokes), keep 32px tall
    for i, ph in enumerate(PHRASES):
        im = render_phrase(ph, font_size=22, pad=4, target_h=32)
        name = ["lost", "steer_l", "steer_r", "track", "radar"][i]
        emit_bmp(out_lines, name, im)
    for text, name, fsize, th in SMALL_LABELS:
        im = render_phrase(text, font_size=fsize, pad=2, target_h=th)
        emit_bmp(out_lines, name, im)
    for text, name, fsize, th in TRACK_HUD:
        im = render_phrase(text, font_size=fsize, pad=2, target_h=th)
        emit_bmp(out_lines, name, im)
    for text, name in RADAR_PICK:
        # 须 ≤128 列，否则 oled.c 截断 bw 会与字模列步进不一致
        im = render_phrase(text, font_size=18, pad=2, target_h=32)
        emit_bmp(out_lines, name, im)
    path = os.path.join(os.path.dirname(__file__), "..", "Core", "Src", "oled_cn_bmps.c")
    path = os.path.normpath(path)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out_lines) + "\n")
    print("Wrote", path)


if __name__ == "__main__":
    main()
